# Generated by Django 4.1 on 2022-09-02 14:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس عنوان')),
                ('description', models.TextField(max_length=2000, verbose_name='توضیحات')),
                ('thumbnail', models.ImageField(default='image/article-image/default/article-default.jpg', upload_to='image/article-image', verbose_name='عکس')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده'), ('r', 'برگشت داده شده')], max_length=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس عنوان')),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده')], default='d', max_length=1, verbose_name='وضعیت')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='blog.category', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['parent__id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('m', 'اطلاعات علمی نادرست'), ('r', 'محتوای نامناسب و توهین آمیز'), ('o', 'موارد دیگر')], max_length=1, verbose_name='دلیل')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_checked', models.BooleanField(default=False, verbose_name='رویت شده است؟')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='مقاله مربوط')),
            ],
            options={
                'verbose_name': 'مقاله برگشت خورده',
                'verbose_name_plural': 'مقالات برگشت خورده',
            },
        ),
        migrations.CreateModel(
            name='ArticleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('m', 'اطلاعات علمی نادرست'), ('r', 'محتوای نامناسب و توهین آمیز'), ('o', 'موارد دیگر')], max_length=1, verbose_name='دلیل')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_checked', models.CharField(choices=[('y', 'بررسی شده است'), ('n', 'بررسی نشده است')], default='n', max_length=1, verbose_name='بررسی شده است؟')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleReport', to='blog.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'مقاله گزارش داده شده',
                'verbose_name_plural': 'مقالات گزارش داده شده',
            },
        ),
        migrations.CreateModel(
            name='ArticleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس عنوان')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='توضیحات')),
                ('thumbnail', models.ImageField(default='image/article-image/default/article-default.jpg', upload_to='image/article-image', verbose_name='عکس')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده'), ('r', 'برگشت داده شده')], max_length=1, verbose_name='وضعیت')),
                ('return_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان اخطار')),
                ('return_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('history_creation_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد تاریخچه')),
                ('change', models.CharField(choices=[('+', 'افزودن'), ('-', 'حذف کردن'), ('∼', 'آپدیت کردن'), ('r', 'برگشت دادن')], max_length=1, verbose_name='نوع تغییر')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articleHistory', to='blog.article', verbose_name='مقاله مربوط')),
                ('article_after_delete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articleHistoryAfterDelete', to='blog.articlehistory', verbose_name='مقاله مربوط (حذف شده)')),
                ('category', models.ManyToManyField(to='blog.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'تاریخچه مقاله',
                'verbose_name_plural': 'تاریخچه مقالات',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='article', to='blog.category', verbose_name='دسته بندی'),
        ),
    ]
